### ISSUE TITLE
Plan to create a separated vte crate?

### ISSUE THREAD

**Issue by sunnyone** [oakes/SolidOak#51]
When I looked for vte wrapper of Rust, I found your SolidOak app uses a forked version of gtk-rs, and it has a vte wrapper. Do you have any plan to separate the implementation of vte wrapper as a crate?

**Comment by oakes** [comment]
I always wanted to do that, but at the time I wrote it I was not able to break it into a separate crate because it uses macros from gtk-rs, which were not able to cross crate boundaries. I haven't checked recently on whether that has changed; if it has, I would definitely be willing to break it out.

**Comment by sunnyone** [comment]
I have understood the reason why it's forked.

I don't read the code in detail, do "macros from gtk-rs" mean "struct_Widget!", "impl_drop!", or "impl_TraitWidget!" ? These macros seem to be disappeared in the current gtk-rs/gtk repository. The style of code for widgets seem to be completely changed (I see: old:gtk/src/widgets/text_view.rs , new:gtk/src/auto/text_view.rs). It may be worth to check the new implementation.

**Comment by dns2utf8** [comment]
Any news on this?

**Comment by oakes** [comment]
Better late than never :D I am now using a separate create for vte:

https://github.com/oakes/vte-rs
